### ISSUE TITLE
This is not really a issue, is a form of recognise your incredible work along any Unix system (even on phones whith SailfishOS

### ISSUE THREAD

**Issue by ferlanero** [astrolince/hosty#21]
I have been using hosty on my Unix-like machines for years. But it wasn't till yesterday when I realize how powerful is this script for ad blocking purposes even on... mobile phones! Yes, you have read it right. You can run and use hosty perfectly on [Sailfishos.org](https://sailfishos.org/), which means you'll get phone-wide ad blocking by simply following this easy steps: [https://www.linuxleon.org/2019/11/hosty-un-bloqueador-de-anuncios-para.html](https://www.linuxleon.org/2019/11/hosty-un-bloqueador-de-anuncios-para.html)

Hope you take in mind that your incredible work with hosty is working on smartphones too. Thanks a lot for all your efforts!

**Comment by astrolince** [comment]
Hola! Acabo de ver esto, muchas gracias por tomarte el tiempo de escribirlo.

I will take notes on the additional steps you took to make it work because I'm very interested in having a purer Linux on my phone. And it fits into the future projects I'm working on.

As always, if you have any comment or suggestion, reach me out.

Have a great day.
